const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const fmt = n => n == null ? '—' : new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 2 }).format(n);
const pct = n => n == null ? '—' : `${new Intl.NumberFormat('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n)}%`;
const month = c => new Intl.DateTimeFormat('pt-BR', { month: 'short', year: 'numeric' }).format(new Date(`${c}-01T12:00:00`)).replace(' de ', '/');
const domains = { carteira: ['Carteira', 'Manutenção e fidelização', '◈'], fixa: ['Banda Larga', 'Qualidade das vendas fixas', '⌁'], movel: ['Móvel', 'Performance e experiência', '▯'] };
const pulse = [['early-churn-fixa', 'Early Churn Fixa'], ['early-churn-movel', 'Early Churn Móvel'], ['churn-bl', 'Churn Fixa'], ['churn-movel', 'Churn Móvel'], ['saldo-portabilidade', 'Saldo de Portabilidade']];
const band = (value, total = false) => value == null ? '<span class="muted">Sem dados</span>' : `<span class="qsc-band ${total ? 'total-band' : 'indicator-band'} band-${esc(value)}">${total && value === 0 ? 'Sem faixa' : `Faixa ${esc(value)}`}</span>`;
let semester, scopeKey;
const expanded = new Set();

export function renderUnified(company, period, prefix, onEvidence) {
  const key = `${prefix}:${period}`;
  if (scopeKey !== key) { scopeKey = key; semester = Number(period.slice(5)) <= 6 ? 1 : 2; expanded.clear(); }
  const semesters = company.painel_semestral ?? [];
  const renderSemester = () => {
    const data = semesters.find(s => s.semestre === semester);
    document.querySelector('#unified-history').innerHTML = `<div class="unified-head"><div><p class="eyebrow">HISTÓRICO CONSOLIDADO</p><h2>Visão histórica por semestre</h2></div><div class="semester-switch" aria-label="Selecionar semestre">${[1, 2].map(s => `<button type="button" data-semester="${s}" aria-pressed="${s === semester}">${s}º semestre</button>`).join('')}</div></div>${data ? `<div class="table-wrap"><table class="semester-table"><caption>${semester}º semestre de ${esc(data.ano)} · Média dos meses com dados</caption><thead><tr><th>Indicadores</th>${data.competencias.map(c => `<th>${esc(month(c).split('/')[0])}</th>`).join('')}<th>Totalizador</th><th>Pts</th><th>Faixa</th><th>Periodicidade</th></tr></thead><tbody>${data.dominios.map(d => `<tr><th scope="row">QSC ${d.dominio === 'fixa' ? 'Fixa' : domains[d.dominio][0]}</th>${d.meses.map(m => `<td class="${m.nota == null ? 'unavailable' : ''}">${fmt(m.nota)}</td>`).join('')}<td class="semester-total">${fmt(d.nota)}</td><td><strong>${fmt(d.pontos)}</strong></td><td>${band(d.faixa, true)}</td><td class="small">Mensal</td></tr>`).join('')}</tbody></table></div><p class="unified-note">Meses sem dados aparecem como “—” e não entram na média do semestre.</p>` : '<p class="unified-note">Histórico semestral indisponível neste processamento.</p>'}`;
    document.querySelectorAll('[data-semester]').forEach(b => b.onclick = () => { semester = Number(b.dataset.semester); renderSemester(); });
  };
  renderSemester();
  document.querySelector('#unified-pulse').innerHTML = `<div class="unified-head"><div><p class="eyebrow">INDICADORES CRÍTICOS</p><h2>Pulso do mês</h2></div><span class="small">${esc(month(period))}</span></div><div class="pulse-grid">${pulse.map(([id, label]) => {
    const i = company.indicadores.find(m => m.id === id); if (!i) return '';
    return `<button class="pulse-card" data-pulse="${esc(id)}"><span class="pulse-label">${label}</span><span class="pulse-value">${pct(i.valor)}${band(i.faixa)}</span><span class="pulse-foot"><span>Nota <b>${fmt(i.pontos)}</b>/${fmt(i.peso)}</span><span>${fmt(i.numerador)} / ${fmt(i.denominador)}</span></span></button>`;
  }).join('')}</div>`;
  const renderDomains = () => {
    const filter = document.querySelector('#domain-filter').value;
    document.querySelector('#unified-domains').innerHTML = company.dominios.filter(d => !filter || filter === d.dominio).map(d => {
      const meta = domains[d.dominio];
      return `<section class="unified-domain" aria-label="Resumo ${meta[0]}"><div class="unified-head"><div class="domain-title"><span class="domain-icon" aria-hidden="true">${meta[2]}</span><div><p class="eyebrow">${meta[1]}</p><h2>Resumo ${meta[0]}</h2></div></div><div class="domain-rating"><span class="small">${esc(month(period))}${d.parcial ? ' · Parcial' : ''}</span><strong>Nota QSC ${fmt(d.nota)}</strong>${band(d.faixa, true)}<span class="small">${fmt(d.pontos)} pts</span></div></div><div class="table-wrap"><table class="unified-metrics"><thead><tr><th>Indicador</th><th>KPI 1</th><th>KPI 2</th><th>Resultado</th><th>Nota</th><th>Faixa</th><th>Gap</th></tr></thead><tbody>${company.indicadores.filter(i => i.dominio === d.dominio).map(i => {
        const open = expanded.has(i.id);
        return `<tr id="metric-${esc(i.id)}" class="${open ? 'metric-open' : ''}"><td><button class="expand-metric" data-expand="${esc(i.id)}" aria-expanded="${open}" aria-controls="history-${esc(i.id)}"><span class="expand-chevron" aria-hidden="true">${open ? '−' : '+'}</span>${esc(i.nome)}</button></td><td>${fmt(i.numerador)}</td><td>${fmt(i.denominador)}</td><td class="result-value">${pct(i.valor)}</td><td><strong>${fmt(i.pontos)}</strong><span class="muted">/${fmt(i.peso)}</span></td><td>${band(i.faixa)}</td><td class="${i.impacto_no_qsc > 0 ? 'gap-num' : ''}">${fmt(i.impacto_no_qsc)}</td></tr><tr id="history-${esc(i.id)}" ${open ? '' : 'hidden'}><td colspan="7" class="metric-detail"><div class="detail-heading"><div><p class="eyebrow">HISTÓRICO DO INDICADOR</p><p>${esc(i.formula)}</p></div><button class="button" data-source="${esc(i.id)}">Consultar evidências ↗</button></div><div class="metric-history">${(i.historico ?? []).map(p => `<article><span class="small">${esc(month(p.competencia))}</span><strong>${pct(p.valor)}</strong><div><span>Nota ${fmt(p.pontos)}/${fmt(p.maximo)}</span>${band(p.faixa)}</div><small>KPI 1 ${fmt(p.numerador)} · KPI 2 ${fmt(p.denominador)}</small></article>`).join('') || '<p>Histórico indisponível.</p>'}</div><div class="detail-footer"><span>Melhor faixa: <strong>${i.meta == null ? 'Pontuação máxima em todas as faixas' : `${esc(i.meta_operador)} ${pct(i.meta)}`}</strong></span><a href="${prefix}/export/html#indicadores" target="_blank" rel="noopener">Ver no relatório ↗</a></div></td></tr>`;
      }).join('')}</tbody></table></div></section>`;
    }).join('');
    document.querySelectorAll('[data-expand]').forEach(b => b.onclick = () => { expanded.has(b.dataset.expand) ? expanded.delete(b.dataset.expand) : expanded.add(b.dataset.expand); renderDomains(); document.querySelector(`[data-expand="${b.dataset.expand}"]`)?.focus({ preventScroll: true }); });
    document.querySelectorAll('[data-source]').forEach(b => b.onclick = () => onEvidence(b.dataset.source));
  };
  renderDomains();
  document.querySelector('#domain-filter').onchange = renderDomains;
  document.querySelectorAll('[data-pulse]').forEach(b => b.onclick = () => { document.querySelector('#domain-filter').value = ''; expanded.add(b.dataset.pulse); renderDomains(); document.querySelector(`#metric-${b.dataset.pulse}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' }); });

  document.querySelector('#report-hub').innerHTML = `<div class="report-hub-hero"><div><p class="eyebrow">RELATÓRIO EXECUTIVO</p><h2>Da visão unificada<br>ao plano de ação.</h2><p>As notas, os indicadores e os gaps de ${esc(company.empresa_nome)}, na competência ${esc(month(period))}, reunidos em uma apresentação para a gestão.</p><div class="downloads"><a class="button dark" href="${prefix}/export/html#visao" target="_blank" rel="noopener">Abrir relatório completo ↗</a><a class="button" href="${prefix}/export/pdf">Baixar PDF ↓</a></div></div><div class="report-preview" aria-label="Resumo do relatório"><span>QSC / ${esc(month(period))}</span><h3>${esc(company.empresa_nome)}</h3><div>${company.dominios.map(d => `<article><span>${domains[d.dominio][0]}</span><strong>${fmt(d.nota)}</strong></article>`).join('')}</div><p>Indicadores · Gaps · Plano de ação</p></div></div><div class="report-chapters">${[['01', 'Visão executiva', 'As três notas QSC em destaque.', 'visao'], ['02', 'Indicadores e gaps', 'Resultado, pontuação e oportunidades.', 'indicadores'], ['03', 'Plano de ação', 'Tratativas para Fixa e Móvel.', 'plano']].map(([n, title, text, anchor]) => `<a href="${prefix}/export/html#${anchor}" target="_blank" rel="noopener"><span>${n}</span><h3>${title} ↗</h3><p>${text}</p></a>`).join('')}</div>`;
}
