import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

// Browsers normalize inline style line endings before checking a CSP hash.
// Normalize the source too, so the generated hash remains valid on Windows.
const css = (await readFile(new URL('./report.css', import.meta.url), 'utf8'))
  .replace(/^\uFEFF/, '')
  .replace(/\r\n?/g, '\n');
export const reportStyleHash = createHash('sha256').update(css).digest('base64');
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const fmt = value => value === null || value === undefined ? '—' : new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 2 }).format(value);
const domainNames = { carteira: 'Carteira', fixa: 'Fixa', movel: 'Móvel' };
const band = value => value === null ? 'Sem dados' : value === 0 ? 'Sem faixa' : `Faixa ${value}`;
const initials = (name = '') => name.split(/\s+/).filter(Boolean).slice(0, 2).map(s => s[0]).join('');
const sectionTitle = (n, eyebrow, title, description = '') => `<div class="section-heading"><span class="section-number">${n}</span><div><p class="eyebrow">${escape(eyebrow)}</p><h2>${title}</h2>${description ? `<p class="section-description">${description}</p>` : ''}</div></div>`;
const empty = text => `<p class="empty-note">${escape(text)}</p>`;

export function makeHtml(result, company) {
  const e = escape, plan = company.plano_acao;
  const period = result.periodo_referencia;
  const date = new Date(`${period}-01T12:00:00Z`);
  const month = Number.isNaN(date.valueOf()) ? period : new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(date);
  const processed = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long', timeZone: 'America/Sao_Paulo' }).format(new Date(result.data_processamento));
  const calculated = company.indicadores.filter(i => i.pontos !== null).length;
  const availableScores = company.dominios.filter(domain => domain.nota !== null).length;
  const maxGap = Math.max(1, ...company.principais_gaps.map(g => Number(g.impacto) || 0));
  const topGaps = company.principais_gaps.slice(0, 5);
  const highestScore = Math.max(...company.dominios.map(domain => Number(domain.nota) || 0));
  const ownRecords = result.registros.filter(row => row.partnerId === company.empresa_id && row.competence === period);
  const ownSources = new Set(ownRecords.map(row => row.sourceId));
  const sources = result.importacao.fontes.filter(source => ownSources.has(source.id));
  const indicatorTables = company.dominios.map(domain => {
    const indicators = company.indicadores.filter(i => i.dominio === domain.dominio);
    return `<div class="domain-table"><div class="domain-heading"><h3>QSC ${domainNames[domain.dominio]}</h3><p><strong>${fmt(domain.nota)}</strong> / 100 <span class="separator">·</span> ${band(domain.faixa)} <span class="separator">·</span> ${domain.parcial ? 'Cobertura parcial' : 'Cobertura completa'}</p></div><div class="table-scroll"><table><thead><tr><th>Indicador</th><th>Resultado</th><th>Melhor faixa¹</th><th>Pontos</th><th>Gap²</th></tr></thead><tbody>${indicators.map(i => `<tr><td><strong>${e(i.nome)}</strong><span class="formula">${e(i.formula)}</span></td><td>${fmt(i.valor)}${i.valor === null ? '' : '%'}</td><td>${i.meta === null ? '—' : `${e(i.meta_operador)} ${fmt(i.meta)}%`}</td><td class="points">${fmt(i.pontos)}<small> / ${fmt(i.peso)}</small></td><td><span class="${i.impacto_no_qsc > 0 ? 'gap-value' : 'neutral-value'}">${fmt(i.impacto_no_qsc)}</span></td></tr>`).join('')}</tbody></table></div></div>`;
  }).join('');
  const scoreCards = company.dominios.map((domain, i) => {
    const value = Math.max(0, Math.min(100, domain.nota ?? 0));
    return `<article class="score-card"><div class="score-top"><span>0${i + 1} / QSC ${domainNames[domain.dominio]}</span><span class="coverage ${domain.parcial ? 'partial' : ''}">${domain.parcial ? 'Parcial' : 'Completo'}</span></div><div class="score-value">${fmt(domain.nota)}<small>/100</small></div><svg class="score-line" viewBox="0 0 300 5" preserveAspectRatio="none" role="img" aria-label="Nota ${e(domainNames[domain.dominio])}: ${fmt(domain.nota)}"><rect width="300" height="5" rx="2.5" class="track"/><rect width="${value * 3}" height="5" rx="2.5" class="fill"/></svg><div class="score-bottom"><strong>${band(domain.faixa)}</strong><span>${fmt(domain.pontos)} pontos finais</span></div><p class="score-detail">${domain.indicadores_calculados} de ${domain.indicadores_esperados} indicadores calculáveis</p></article>`;
  }).join('');
  const scoreChart = company.dominios.map(domain => {
    const value = Math.max(0, Math.min(100, Number(domain.nota) || 0));
    return `<div class="chart-score"><div class="chart-score-label"><span>QSC ${e(domainNames[domain.dominio])}</span><strong>${fmt(domain.nota)}<small>/100</small></strong></div><div class="chart-track"><span style="width:${value}%"></span></div><div class="chart-scale"><span>0</span><span>100</span></div></div>`;
  }).join('');
  const gapChart = topGaps.map((gap, index) => `<div class="chart-gap"><span class="chart-rank">${String(index + 1).padStart(2, '0')}</span><div><strong>${e(gap.criterio)}</strong><div class="chart-track"><span style="width:${Math.max(0, Number(gap.impacto) || 0) / maxGap * 100}%"></span></div></div><b>${fmt(gap.impacto)}<small> pts</small></b></div>`).join('') || '<p class="chart-empty">Sem gaps calculáveis nesta competência.</p>';
  return `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>Relatório QSC · ${e(company.empresa_nome)} · ${e(period)}</title><style>${css}</style></head>
<body>
<nav class="report-nav" aria-label="Navegação do relatório"><a href="#inicio" class="wordmark"><span class="q-mark">Q</span> QSC <span class="wordmark-sub">EXECUTIVE REPORT</span></a><div><a href="#visao">Visão executiva</a><a href="#indicadores">Indicadores</a><a href="#plano">Plano de ação</a></div><span class="print-hint">Imprimir / salvar PDF: Ctrl + P</span></nav>
<main class="report">
<header class="cover" id="inicio"><div class="cover-main"><div class="edition"><span class="edition-line"></span> QUALIDADE COMERCIAL <span class="edition-year">${e(period.slice(0, 4))}</span></div><p class="cover-kicker">RELATÓRIO EXECUTIVO</p><h1>Qualidade,<br>perspectiva<br><em>e ação.</em></h1><div class="company-lockup"><span class="company-mark">${e(initials(company.empresa_nome))}</span><div><h2>${e(company.empresa_nome)}</h2><p>${company.cnpj_empresa ? `CNPJ ${e(company.cnpj_empresa)}` : 'Empresa identificada pela base importada'}</p></div></div><div class="cover-meta"><div><span>COMPETÊNCIA</span><strong>${e(month)}</strong></div><div><span>EMISSÃO</span><strong>${e(processed)}</strong></div></div></div><aside class="cover-aside"><div class="aside-monogram" aria-hidden="true">Q.</div><div class="aside-top"><span>QSC</span><span>GESTÃO DA<br>QUALIDADE</span></div><p class="aside-statement">Uma leitura<br>precisa para<br><em>decisões melhores.</em></p><div class="contents-mini"><span>NESTA EDIÇÃO</span><a href="#visao"><b>01</b> Visão executiva <i>↗</i></a><a href="#indicadores"><b>02</b> Performance dos indicadores <i>↗</i></a><a href="#painel"><b>03</b> Painel de performance <i>↗</i></a><a href="#gaps"><b>04</b> Gaps e diagnóstico <i>↗</i></a><a href="#plano"><b>05</b> Plano de ação <i>↗</i></a><a href="#tratativas"><b>06</b> Carteira de tratativas <i>↗</i></a></div><div class="aside-footer"><span>${calculated}/${company.indicadores.length}</span> indicadores calculáveis<br><small>Três domínios. Uma visão da operação.</small></div></aside></header>
<div class="report-body">
<section id="visao" class="report-section">${sectionTitle('01', 'KPIs PRINCIPAIS', 'As três notas <em>que orientam a leitura.</em>', `Competência de ${e(month)}. Resultados apurados individualmente para ${e(company.empresa_nome)}.`)}
<div class="score-grid">${scoreCards}</div><p class="method-inline">Os três QSCs são independentes. A metodologia não define uma nota geral combinada. Notas parciais consideram somente indicadores calculáveis.</p>
<div class="facts"><div><strong>${company.principais_gaps.length.toString().padStart(2, '0')}</strong><span>Indicadores com diferença<br>para a pontuação máxima</span></div><div><strong>${calculated}/${company.indicadores.length}</strong><span>Indicadores calculáveis<br>na competência</span></div><div><strong>${availableScores}/${company.dominios.length}</strong><span>Notas QSC disponíveis<br>para avaliação</span></div></div></section>

<section id="indicadores" class="report-section">${sectionTitle('02', 'PERFORMANCE DOS INDICADORES', 'Precisão em <em>cada critério.</em>', 'Resultados, faixas de referência e pontuação reunidos em uma leitura comparável.')}<div class="indicator-tables">${indicatorTables}</div><div class="footnotes"><p>¹ Limiar da faixa de maior pontuação, não uma meta contratual. “—” indica referência ou resultado indisponível. Qualidade Aceite: em agosto, 20 pontos em todas as faixas; nos demais meses, 0, 10, 14 ou 20 pontos conforme os limites de 85%, 90% e 95%.</p><p>² Diferença entre a pontuação máxima e a obtida. Não representa previsão de recuperação. Penalidades negativas podem produzir um gap superior ao máximo do indicador.</p></div></section>
<section id="painel" class="report-section executive-dashboard">${sectionTitle('03', 'PAINEL DE PERFORMANCE', 'A decisão, <em>em uma página.</em>', 'Visualizações consolidadas a partir das notas e gaps calculados. Os domínios não são combinados em uma nota geral.')}
<div class="executive-intro"><p class="lead">${e(plan.resumo_executivo)}</p><aside class="editor-note"><span class="eyebrow">BASE DO DIAGNÓSTICO</span><p>${e(plan.origem)}</p>${plan.modelo ? `<small>Modelo: ${e(plan.modelo)}</small>` : '<small>Texto elaborado a partir dos resultados calculados.</small>'}</aside></div>
<div class="kpi-grid"><article class="kpi-card kpi-accent"><span>MAIOR NOTA QSC</span><strong>${fmt(highestScore)}<small>/100</small></strong><p>Maior resultado entre os domínios apurados.</p></article><article class="kpi-card"><span>MAIOR GAP</span><strong>${topGaps[0] ? fmt(topGaps[0].impacto) : '—'}<small>${topGaps[0] ? ' pts' : ''}</small></strong><p>${topGaps[0] ? e(topGaps[0].criterio) : 'Nenhum gap calculável.'}</p></article><article class="kpi-card"><span>COBERTURA</span><strong>${calculated}<small>/${company.indicadores.length}</small></strong><p>Indicadores com resultado disponível.</p></article><article class="kpi-card"><span>GAPS ATIVOS</span><strong>${company.principais_gaps.length}<small> itens</small></strong><p>Diferenças para a pontuação máxima.</p></article></div>
<div class="chart-grid"><article class="insight-chart score-chart"><div class="chart-title"><span>NOTAS POR DOMÍNIO</span><p>Leitura comparativa de cada QSC</p></div>${scoreChart}</article><article class="insight-chart gap-chart"><div class="chart-title"><span>PRINCIPAIS GAPS</span><p>Diferença em pontos para o máximo</p></div>${gapChart}</article></div></section>
<section id="gaps" class="report-section">${sectionTitle('04', 'GAPS E DIAGNÓSTICO', 'Onde concentrar <em>a análise.</em>', 'Indicadores ordenados pela diferença de pontos. A ordenação não define prioridade individual de clientes.')}<div class="gap-list">${company.principais_gaps.map((g, i) => `<article class="gap-row"><span class="gap-index">${String(i + 1).padStart(2, '0')}</span><div class="gap-main"><h3>${e(g.criterio)}</h3><p>${e(g.descricao)}</p><svg class="gap-line" viewBox="0 0 400 4" preserveAspectRatio="none" aria-hidden="true"><rect width="400" height="4" rx="2" class="track"/><rect width="${Math.max(0, Number(g.impacto) || 0) / maxGap * 400}" height="4" rx="2" class="fill"/></svg></div><strong class="gap-total">${fmt(g.impacto)}<small>pontos</small></strong></article>`).join('') || empty('Nenhum gap calculável nesta competência. Avalie a cobertura dos indicadores antes de concluir.')}</div><div class="diagnosis"><span class="eyebrow">LEITURA DO CENÁRIO</span><h3>Diagnóstico executivo</h3><p>${e(plan.diagnostico)}</p><span class="diagnosis-source">${e(plan.origem)}</span></div></section>
<section id="plano" class="report-section">${sectionTitle('05', 'PLANO DE AÇÃO', 'Da leitura <em>à execução.</em>', 'Ações recomendadas para revisão da gestão. Responsáveis, prazos e impactos são propostas, quando disponíveis.')}
<div class="action-list">${plan.acoes_prioritarias.map((action, index) => `${index > 0 && index % 6 === 0 ? `<div class="action-continuation"><span>05 / PLANO DE AÇÃO</span><h3>Da leitura à execução <em>— continuação</em></h3><p>Ações ${index + 1} a ${Math.min(index + 6, plan.acoes_prioritarias.length)} de ${plan.acoes_prioritarias.length}</p></div>` : ''}<article class="action-card"><div class="action-index">${String(index + 1).padStart(2, '0')}</div><div class="action-content"><h3>${e(action.acao)}</h3><p>${e(action.justificativa)}</p><div class="action-meta"><div><span>RESPONSÁVEL SUGERIDO</span><strong>${e(action.responsavel_sugerido)}</strong></div><div><span>PRAZO SUGERIDO</span><strong>${e(action.prazo_sugerido)}</strong></div></div><div class="expected"><span>IMPACTO ESPERADO</span><p>${e(action.impacto_esperado)}</p></div></div></article>`).join('') || empty('Nenhuma ação gerada para esta competência.')}</div></section>
<section id="tratativas" class="report-section">${sectionTitle('06', 'CARTEIRA DE TRATATIVAS', 'Acompanhamento <em>com evidência.</em>', 'Casos confirmados pelo usuário. A metodologia oficial não estabelece classificação ou prioridade individual por CNPJ.')}
${company.cnpjs_para_tratativa.map(c => `<article class="treatment-card"><div class="treatment-top"><div><span class="eyebrow">${e(c.cnpj)}</span><h3>${e(c.razao_social || 'Razão social não informada')}</h3></div><span class="priority">${e(c.prioridade)}<small>prioridade manual</small></span></div><div class="treatment-details"><div><span>CRITÉRIO</span><p>${e(c.criterio_afetado)}</p></div><div><span>MOTIVO</span><p>${e(c.motivo_tratativa)}</p></div><div class="treatment-action"><span>AÇÃO RECOMENDADA</span><p>${e(c.acao_recomendada)}</p></div></div><p class="trace">REGISTROS DE ORIGEM <span>${e(c.registros.join(' · '))}</span></p></article>`).join('') || empty('Nenhum CNPJ confirmado para tratativa. Os casos vinculados aos indicadores com gap permanecem disponíveis para revisão na aplicação.')}
<div class="closing"><p class="eyebrow">PRÓXIMO CICLO</p><h3>Transformar evidência<br>em <em>acompanhamento contínuo.</em></h3><p>Validar os gaps com as linhas de origem, atribuir responsáveis aos casos confirmados e acompanhar a próxima competência. A evolução deve considerar a cobertura das bases e a revisão das sugestões pela gestão.</p></div></section>
<section class="methodology"><div><p class="eyebrow">NOTA METODOLÓGICA</p><h3>Confiança está<br>na rastreabilidade.</h3></div><div><p>Regras oficiais: ${result.fontes_regras.map(e).join(' e ')}. O cálculo usa numeradores e denominadores da mesma empresa e competência. Duplicidades são sinalizadas e preservadas conforme a regra documentada.</p><p>${fmt(ownRecords.length)} registros da empresa nesta competência, provenientes de ${sources.length} arquivo(s). Os cálculos preservam a rastreabilidade entre cada indicador e suas linhas de origem.</p><details><summary>Consultar arquivos de origem e versão das regras</summary>${sources.map(s => `<p class="source-file"><strong>${e(s.arquivo)}</strong><code>SHA-256 ${e(s.sha256)}</code></p>`).join('')}${Object.entries(result.regras_sha256 ?? {}).map(([file, sha]) => `<p class="source-file"><strong>${e(file)}</strong><code>SHA-256 ${e(sha)}</code></p>`).join('')}</details></div></section>
</div><footer class="report-footer"><span class="footer-brand">QSC <small>GESTÃO DA QUALIDADE</small></span><span>${e(company.empresa_nome)} · ${e(period)}</span><span>Relatório executivo</span></footer>
</main></body></html>`;
}

